# Generated by Django 5.1.7 on 2025-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="date",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="description",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="time",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="title",
        ),
        migrations.RemoveField(
            model_name="agenda",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="agenda",
            name="email",
            field=models.EmailField(default="exemplo@email.com", max_length=254),
        ),
        migrations.AddField(
            model_name="agenda",
            name="endereco",
            field=models.TextField(default="Endereço não informado", max_length=100),
        ),
        migrations.AddField(
            model_name="agenda",
            name="nome",
            field=models.CharField(default="Nome não informado", max_length=100),
        ),
        migrations.AddField(
            model_name="agenda",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
