# Generated by Django 5.1.7 on 2025-03-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_remove_agenda_created_at_remove_agenda_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="endereco",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
