# Generated by Django 5.1.7 on 2025-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_alter_agenda_email_alter_agenda_endereco_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
    ]
