# Generated by Django 5.1.7 on 2025-03-18 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0004_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="agenda.categoria",
            ),
            preserve_default=False,
        ),
    ]
